CREATE TABLE IF NOT EXISTS lab.nplus1_authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS lab.nplus1_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    CONSTRAINT fk_nplus1_books_author FOREIGN KEY (author_id) REFERENCES lab.nplus1_authors (id)
);

CREATE INDEX IF NOT EXISTS idx_nplus1_books_author_id ON lab.nplus1_books (author_id);

INSERT INTO lab.nplus1_authors (id, name)
SELECT author_id, 'Author ' || author_id
FROM generate_series(1, 10) AS author_id
ON CONFLICT (id) DO NOTHING;

INSERT INTO lab.nplus1_books (id, author_id, title)
SELECT ((author_id - 1) * 5) + book_no,
       author_id,
       'Author ' || author_id || ' Book ' || book_no
FROM generate_series(1, 10) AS author_id
CROSS JOIN generate_series(1, 5) AS book_no
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('lab.nplus1_authors', 'id'), COALESCE((SELECT MAX(id) FROM lab.nplus1_authors), 1));
SELECT setval(pg_get_serial_sequence('lab.nplus1_books', 'id'), COALESCE((SELECT MAX(id) FROM lab.nplus1_books), 1));

